async function QuickJSRaw(moduleArg={}){var moduleRtn;var c=moduleArg,aa=!!globalThis.window,n=!!globalThis.WorkerGlobalScope;function q(a){a={log:a||function(){}};for(const d of q.Qa)d(a);return c.quickJSEmscriptenExtensions=a}q.Qa=[];c.quickjsEmscriptenInit=q;q.Qa.push(a=>{a.getWasmMemory=function(){return r}});var t="./this.program",ba=import.meta.url,u="",v,w;
if(aa||n){try{u=(new URL(".",ba)).href}catch{}n&&(w=a=>{var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});v=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var y=console.log.bind(console),z=console.error.bind(console),A,B=!1,C,D,E,F,G,H,I,J,K=!1;
function L(){var a=r.buffer;c.HEAP8=F=new Int8Array(a);new Int16Array(a);c.HEAPU8=G=new Uint8Array(a);new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);new Float32Array(a);new Float64Array(a);J=new BigInt64Array(a);new BigUint64Array(a)}function M(a){c.onAbort?.(a);a="Aborted("+a+")";z(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");E?.(a);throw a;}var N;
async function ca(a){if(!A)try{var d=await v(a);return new Uint8Array(d)}catch{}if(a==N&&A)a=new Uint8Array(A);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}async function da(a,d){try{var b=await ca(a);return await WebAssembly.instantiate(b,d)}catch(e){z(`failed to asynchronously prepare wasm: ${e}`),M(e)}}
async function ea(a){var d=N;if(!A)try{var b=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){z(`wasm streaming compile failed: ${e}`),z("falling back to ArrayBuffer instantiation")}return da(d,a)}class O{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var P=a=>{for(;0<a.length;)a.shift()(c)},fa=[],ha=[],ia=()=>{var a=c.preRun.shift();ha.push(a)},Q=!0,r,ja=new TextDecoder,ka=(a,d,b,e)=>{b=d+b;if(e)return b;for(;a[d]&&!(d>=b);)++d;return d},R=(a,d,b)=>a?ja.decode(G.subarray(a,ka(G,a,d,b))):"",S=0,la=[0,31,60,91,121,152,182,213,244,274,305,335],ma=[0,31,59,90,120,151,181,212,243,273,304,334],T={},na=a=>{if(!(a instanceof O||"unwind"==a))throw a;},oa=a=>{C=a;Q||0<S||(c.onExit?.(a),B=!0);throw new O(a);},pa=a=>{if(!B)try{a()}catch(d){na(d)}finally{if(!(Q||
0<S))try{C=a=C,oa(a)}catch(d){na(d)}}},U=(a,d,b)=>{var e=G;if(!(0<b))return 0;var f=d;b=d+b-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(d>=b)break;e[d++]=h}else if(2047>=h){if(d+1>=b)break;e[d++]=192|h>>6;e[d++]=128|h&63}else if(65535>=h){if(d+2>=b)break;e[d++]=224|h>>12;e[d++]=128|h>>6&63;e[d++]=128|h&63}else{if(d+3>=b)break;e[d++]=240|h>>18;e[d++]=128|h>>12&63;e[d++]=128|h>>6&63;e[d++]=128|h&63;g++}}e[d]=0;return d-f},V={},qa=()=>{if(!W){var a={USER:"web_user",LOGNAME:"web_user",
PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:t||"./this.program"},d;for(d in V)void 0===V[d]?delete a[d]:a[d]=V[d];var b=[];for(d in a)b.push(`${d}=${a[d]}`);W=b}return W},W,X=a=>{for(var d=0,b=0;b<a.length;++b){var e=a.charCodeAt(b);127>=e?d++:2047>=e?d+=2:55296<=e&&57343>=e?(d+=4,++b):d+=3}return d},ra=[null,[],[]],ua=(a,d,b,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=X(k)+1;var p=Y(l);U(k,p,l);l=p}return l},array:k=>
{var l=Y(k.length);F.set(k,l);return l}};a=c["_"+a];var g=[],h=0;if(e)for(var m=0;m<e.length;m++){var x=f[b[m]];x?(0===h&&(h=sa()),g[m]=x(e[m])):g[m]=e[m]}b=a(...g);return b=function(k){0!==h&&ta(h);return"string"===d?R(k):"boolean"===d?!!k:k}(b)};c.wasmMemory?r=c.wasmMemory:r=new WebAssembly.Memory({initial:(c.INITIAL_MEMORY||16777216)/65536,maximum:32768});L();c.noExitRuntime&&(Q=c.noExitRuntime);c.print&&(y=c.print);c.printErr&&(z=c.printErr);c.wasmBinary&&(A=c.wasmBinary);c.thisProgram&&(t=c.thisProgram);
if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.shift()();c.cwrap=(a,d,b,e)=>{var f=!b||b.every(g=>"number"===g||"boolean"===g);return"string"!==d&&f&&!e?c["_"+a]:(...g)=>ua(a,d,b,g)};c.UTF8ToString=R;c.stringToUTF8=(a,d,b)=>U(a,d,b);c.lengthBytesUTF8=X;
var va,ta,Y,sa,wa={b:(a,d,b,e)=>M(`Assertion failed: ${R(a)}, at: `+[d?R(d):"unknown filename",b,e?R(e):"unknown function"]),r:()=>M(""),l:()=>{Q=!1;S=0},m:function(a,d){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);H[d>>2]=a.getSeconds();H[d+4>>2]=a.getMinutes();H[d+8>>2]=a.getHours();H[d+12>>2]=a.getDate();H[d+16>>2]=a.getMonth();H[d+20>>2]=a.getFullYear()-1900;H[d+24>>2]=a.getDay();var b=a.getFullYear();H[d+28>>2]=(0!==b%4||0===b%100&&0!==b%400?ma:la)[a.getMonth()]+
a.getDate()-1|0;H[d+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();H[d+32>>2]=(b!=e&&a.getTimezoneOffset()==Math.min(e,b))|0},j:(a,d)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!d)return 0;var b=setTimeout(()=>{delete T[a];pa(()=>va(a,performance.now()))},d);T[a]={id:b,Ra:d};return 0},n:(a,d,b,e)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();
I[a>>2]=60*Math.max(g,f);H[d>>2]=Number(g!=f);d=h=>{var m=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=d(g);d=d(f);f<g?(U(a,b,17),U(d,e,17)):(U(a,e,17),U(d,b,17))},q:function(a,d,b){if(!(0<=a&&3>=a))return 28;J[b>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},p:()=>Date.now(),k:a=>{var d=G.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=d*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,e)/65536))-r.buffer.byteLength+65535)/65536|0;try{r.grow(e);L();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},e:(a,d)=>{var b=0,e=0,f;for(f of qa()){var g=d+b;I[a+e>>2]=g;b+=U(f,g,Infinity)+1;e+=4}return 0},f:(a,d)=>{var b=qa();I[a>>2]=b.length;a=0;for(var e of b)a+=X(e)+1;I[d>>2]=a;return 0},d:()=>52,o:function(){return 70},c:(a,d,b,e)=>{for(var f=0,g=0;g<b;g++){var h=I[d>>2],m=I[d+4>>2];d+=8;for(var x=0;x<m;x++){var k=a,l=G[h+x],p=ra[k];0===l||10===l?(k=1===
k?y:z,l=ka(p,0),l=ja.decode(p.buffer?p.subarray(0,l):new Uint8Array(p.slice(0,l))),k(l),p.length=0):p.push(l)}f+=m}I[e>>2]=f;return 0},a:r,s:oa,t:function(a,d,b,e,f){return c.callbacks.callFunction(void 0,a,d,b,e,f)},i:function(a){return c.callbacks.shouldInterrupt(void 0,a)},h:function(a,d,b){b=R(b);return c.callbacks.loadModuleSource(void 0,a,d,b)},g:function(a,d,b,e){b=R(b);e=R(e);return c.callbacks.normalizeModule(void 0,a,d,b,e)},u:function(a,d){c.callbacks.freeHostRef(void 0,a,d)}},Z;
Z=await (async function(){function a(b){b=Z=b.exports;c._malloc=b.w;c._QTS_Throw=b.x;c._QTS_NewError=b.y;c._QTS_RuntimeSetMemoryLimit=b.z;c._QTS_RuntimeComputeMemoryUsage=b.A;c._QTS_RuntimeDumpMemoryUsage=b.B;c._QTS_RecoverableLeakCheck=b.C;c._QTS_BuildIsSanitizeLeak=b.D;c._QTS_RuntimeSetMaxStackSize=b.E;c._QTS_GetUndefined=b.F;c._QTS_GetNull=b.G;c._QTS_GetFalse=b.H;c._QTS_GetTrue=b.I;c._QTS_NewHostRef=b.J;c._QTS_GetHostRefId=b.K;c._QTS_NewRuntime=b.L;c._QTS_FreeRuntime=b.M;c._free=b.N;
c._QTS_NewContext=b.O;c._QTS_FreeContext=b.P;c._QTS_FreeValuePointer=b.Q;c._QTS_FreeValuePointerRuntime=b.R;c._QTS_FreeVoidPointer=b.S;c._QTS_FreeCString=b.T;c._QTS_DupValuePointer=b.U;c._QTS_NewObject=b.V;c._QTS_NewObjectProto=b.W;c._QTS_NewArray=b.X;c._QTS_NewArrayBuffer=b.Y;c._QTS_NewFloat64=b.Z;c._QTS_GetFloat64=b._;c._QTS_NewString=b.$;c._QTS_GetString=b.aa;c._QTS_GetArrayBuffer=b.ba;c._QTS_GetArrayBufferLength=b.ca;c._QTS_NewSymbol=b.da;c._QTS_GetSymbolDescriptionOrKey=b.ea;c._QTS_IsGlobalSymbol=
b.fa;c._QTS_IsJobPending=b.ga;c._QTS_ExecutePendingJob=b.ha;c._QTS_GetProp=b.ia;c._QTS_GetPropNumber=b.ja;c._QTS_SetProp=b.ka;c._QTS_DefineProp=b.la;c._QTS_GetOwnPropertyNames=b.ma;c._QTS_Call=b.na;c._QTS_ResolveException=b.oa;c._QTS_Dump=b.pa;c._QTS_Eval=b.qa;c._QTS_GetModuleNamespace=b.ra;c._QTS_Typeof=b.sa;c._QTS_GetLength=b.ta;c._QTS_IsEqual=b.ua;c._QTS_GetGlobalObject=b.va;c._QTS_NewPromiseCapability=b.wa;c._QTS_PromiseState=b.xa;c._QTS_PromiseResult=b.ya;c._QTS_TestStringArg=b.za;c._QTS_GetDebugLogEnabled=
b.Aa;c._QTS_SetDebugLogEnabled=b.Ba;c._QTS_BuildIsDebug=b.Ca;c._QTS_BuildIsAsyncify=b.Da;c._QTS_NewFunction=b.Ea;c._QTS_ArgvGetJSValueConstPointer=b.Fa;c._QTS_RuntimeEnableInterruptHandler=b.Ga;c._QTS_RuntimeDisableInterruptHandler=b.Ha;c._QTS_RuntimeEnableModuleLoader=b.Ia;c._QTS_RuntimeDisableModuleLoader=b.Ja;c._QTS_bjson_encode=b.Ka;c._QTS_bjson_decode=b.La;va=b.Ma;ta=b.Na;Y=b.Oa;sa=b.Pa;return Z}var d={a:wa};if(c.instantiateWasm)return new Promise(b=>{c.instantiateWasm(d,(e,f)=>{b(a(e,f))})});
N??=c.locateFile?c.locateFile?c.locateFile("emscripten-module.wasm",u):u+"emscripten-module.wasm":(new URL("emscripten-module.wasm",import.meta.url)).href;return a((await ea(d)).instance)}());
(function(){function a(){c.calledRun=!0;if(!B){K=!0;Z.v();D?.(c);c.onRuntimeInitialized?.();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var d=c.postRun.shift();fa.push(d)}P(fa)}}if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ia();P(ha);c.setStatus?(c.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>c.setStatus(""),1);a()},1)):a()})();K?moduleRtn=c:moduleRtn=new Promise((a,d)=>{D=a;E=d});
;return moduleRtn}export default QuickJSRaw;
