#!/usr/bin/env node
// gen-farm-worker.test.mjs — offline self-test for scripts/gen-farm-worker.mjs (FARM-WORKER-GEN-1).
//
// Proves, with NO network and NO gh calls:
//   1. GOLDEN BYTES — generated aspire worker equals the pinned golden (sha256 + length), taken
//      from the canonical family file (ainumbers-farm-aspire@c3fd422c, BOM stripped, hp's lane
//      pins carried in). Any template edit that changes aspire's bytes turns this red.
//   2. TOKEN ROUND-TRIP — reverse-substituting each bus's token values out of its generated bytes
//      reproduces the template byte-for-byte, for every bus (the generator adds nothing else).
//   3. PINS + DEFECT ABSENCE — hp's explicit lane pins are present (step `--provider nous`, muse
//      `-m opencode/muse-spark-1.3-contributor-free`); the defects the audit measured are absent
//      (no UTF-8 BOM, no stray codebuddy `-y`, no unsubstituted @@ tokens).
//   4. PER-BUS IDENTITY — every output is distinct and each carries its own machine/bus/npmRoot
//      (five buses since OMEN-BUS-1, 2026-09-18; the count is taken from the BUSES list, not pinned).
//
// Usage: node scripts/gen-farm-worker.test.mjs   (prints PASS lines; exit 1 on any failure)

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { generateWorker, loadTemplate, TEMPLATE_PATH } from './gen-farm-worker.mjs';

// Re-pinned 2026-09-18 (Fable, Tim-directed) for: opencode model rotation + stdin close, process-tree
// kill on timeout, 3-deferral cap, UTC stamp on non-quota .FAILED, heartbeat on sync failure.
// Previous golden: 24456 bytes, e4b0d24b67604f805c06af8209f079304eb108ce0ea57a3bdfc660737eab0f3d.
// FARM-WORKER-DIRTY-TREE-1 (2026-09-18) built the dirty-tree fix but could NOT test or roll it out
// (no PowerShell execution in that session); its template + this file's re-pin (37518 bytes,
// 3727bcd4a8bd68420357c2ff0d69773db7f1e79c30a5221a814915cbcc8a6ce4) are parked under
// research/FARM-WORKER-DIRTY-TREE-1/ so the five buses and this gate stay green meanwhile.
// Re-pinned 2026-09-19 (FARM-HARNESS-ENV-SCRUB-1): allowlisted child environment, per-run TEMP,
// names-only log line, secret-name self-check. Previous golden: 30922 bytes,
// 5fd773b3d16999c21c4d590d1feb8662c3e10f4188d933e28b82777f4c86056a.
// Re-pinned 2026-09-20 (third pass, Tim: "rename the step lane to hermes, the muse lane to
// opencode — that's the harness"): lane keys are now the harness names, a claim-time alias keeps
// legacy `harness: step`/`muse` taskings running, and the nemotron ultra/lightning patterns are
// REMOVED from the opencode pool at Tim's call (9 -> 7 patterns).
// Previous golden: 37331 chars, 90814932eeb33f3b86ea26d0096ea012e3ee973949efb46ac6b241f337beb0f0.
// Re-pinned 2026-09-24 (FARM-WORKER-CODEBUDDY-PATH-1): the workbuddy lane's dead cli\dist\codebuddy.js
// entry (desktop CLI 2.147.0) moved to cli\bin\codebuddy — RequireFile + ArgFormat only.
// Previous golden: 37539 bytes, 5a3b5fa0b58dcbf8c3b053642ae72d03f50f6942b1010189ff88d52730fc859a.
// Re-pinned 2026-09-29 (FARM-WORKER-FAIL-FORWARD-1): a model-fault failure (timeout, clean exit
// with no report, or a model-side tail signature) now retries on the NEXT rotation id inside the
// same dispatch, capped at 3 attempts — Tim: "once hy4-preview runs out of session, try DeepSeek
// v4.1". Scratch dir recreated per attempt; non-model-fault failures land unchanged.
// Previous golden: 37828 bytes, 4302bb3cc8c7151a230d7e0a65af0dced59d1d4f0337161dc03a247568c41e58.
// Re-pinned 2026-10-02 (hermes/step restore): the 2026-09-20 dead pair (solar-pro4, longcat-2.0)
// replaced with the Nous portal's six free ids, probed READY on the Omen 2026-10-02.
// Previous golden: 39893 bytes, 7d10335c864522df4f84c9bc9fa71897ae1aed45cc02c8680e354bdc0aa85c9d.
// Re-pinned 2026-10-04 (WORKBUDDY-DEEPSEEK-ONLY-1): the workbuddy lane runs DeepSeek v4.1 Flash
// only — hy4-preview / hy3 / fast-model / balanced-model dropped from its rotation (Hy4/Hy3 need
// a /login session the farm does not keep; hp's T5-WMC-46921B9F failed "Authentication required.
// Please use /login" on hy4-preview, farm-watch 2026-10-04T18:25:30Z). On DeepSeek exhaustion the
// task defers; it never falls to another model. Fail-forward logic unchanged — in a single-entry
// list it re-tries the same id up to $maxAttempts.
// Previous golden: 40469 bytes, 3c033b252230adda8d9b75eb61d54006912813202d65287c0efec81328b14b8f.
// Re-pinned 2026-10-05 (FARM-WORKER-HP-OMEN-RECONCILE-1): hp's three 2026-10-03 sync-deadlock
// fixes folded into the template (Invoke-Git TrimEnd not Trim; Sync-Repo self-heal on
// `git status --porcelain -z` with NUL-or-newline split + add -A; RUNNING marker kept when the
// commit landed but the push was rejected) and omen's 2026-09-30 heartbeat sync-before-push
// block folded (FARM-HERMES-SWAP-1 memorial open item 1, commit 41f070c5f: fetch + rev-list
// --count + pull --rebase before the heartbeat push; advisory only, never blocks a report).
// Previous golden: 40051 bytes, 55abf63a45be27ce5347c075aee454de1d84b83b3c061f73852091e414937ebe.
// Re-pinned 2026-10-07 (KILO-FALLBACK-LANE-1, Tim-directed: "if a specific bus/lane has a problem
// with a harness, they can try to use kilo auto"): the kilo lane added — headless `kilo run
// --auto -m kilo/kilo-auto/free` through the Kilo CLI (@kilocode/cli 7.8.8, installed on all five
// laptops + the Omen that day), the gateway's Auto Free router as a single-entry literal
// rotation, RequireFile gated on the gateway credential file so the lane is inert (defer, never
// fail) until the per-machine login, and an auth-fault tail signature routed to DEFERRED.
// Previous golden: 45160 bytes, 2a3116ef92db466617b5a5f05ba6c24f67df8b84b9b00430c7797b9b40cab56c.
const GOLDEN = { bus: 'aspire', bytes: 47414, sha256: '61c423344742cba9080906033fc4f8accbe67f2434bcb74af00eebdf4e197a36' };  // 2026-10-07 KILO-FALLBACK-LANE-1: kilo lane (gateway Auto Free router, credential-gated) + auth-fault DEFERRED signature; previous golden 45160/2a3116ef92db
const BUSES = ['hp', 'ps', 'nitro', 'aspire', 'omen', 'msi'];   // MSI-BUS-1 (2026-09-20): sixth bus
const TOKEN_VALUES = {
  hp: { '@@MACHINE@@': 'hp', '@@BUS@@': 'hp', '@@NPMROOT@@': '$env:APPDATA\\npm' },
  ps: { '@@MACHINE@@': 'prostar', '@@BUS@@': 'ps', '@@NPMROOT@@': '$env:APPDATA\\npm' },
  nitro: { '@@MACHINE@@': 'nitro', '@@BUS@@': 'nitro', '@@NPMROOT@@': '$env:LOCALAPPDATA\\hermes\\node' },
  aspire: { '@@MACHINE@@': 'aspire', '@@BUS@@': 'aspire', '@@NPMROOT@@': '$env:LOCALAPPDATA\\hermes\\node' },
  omen: { '@@MACHINE@@': 'omen', '@@BUS@@': 'omen', '@@NPMROOT@@': '$env:APPDATA\\npm' },   // OMEN-BUS-1
  msi: { '@@MACHINE@@': 'msi', '@@BUS@@': 'msi', '@@NPMROOT@@': '$env:LOCALAPPDATA\\hermes\\node' },   // MSI-BUS-1 (2026-09-20)
};

const failures = [];
function assert(cond, label) {
  console.log(`  ${cond ? 'PASS' : 'FAIL'}: ${label}`);
  if (!cond) failures.push(label);
}

console.log(`gen-farm-worker.test.mjs — template ${TEMPLATE_PATH}`);

// 1. golden bytes (aspire — the canonical family, no-BOM form)
const aspire = generateWorker(GOLDEN.bus);
const aspireSha = createHash('sha256').update(aspire).digest('hex');
assert(aspire.length === GOLDEN.bytes, `golden length ${aspire.length} === ${GOLDEN.bytes}`);
assert(aspireSha === GOLDEN.sha256, `golden sha256 ${aspireSha} === ${GOLDEN.sha256}`);
assert(aspire.charCodeAt(0) !== 0xfeff, 'golden bytes carry no UTF-8 BOM');
assert(!aspire.includes(' -y '), 'golden bytes carry no stray codebuddy -y');

// 2. token round-trip for every bus: un-substitute at the anchored token sites -> template
const template = loadTemplate();
function unSubstitute(bus, g) {
  const { '@@MACHINE@@': machine, '@@BUS@@': busName, '@@NPMROOT@@': npmRoot } = TOKEN_VALUES[bus];
  return g
    .replaceAll(`$Machine = '${machine}'`, `$Machine = '@@MACHINE@@'`)
    .replaceAll(`'HEARTBEAT-${busName}.md'`, `'HEARTBEAT-@@BUS@@.md'`)
    .replaceAll(`'# HEARTBEAT-${busName} - one line`, `'# HEARTBEAT-@@BUS@@ - one line`)
    .replaceAll(`'notes/HEARTBEAT-${busName}.md'`, `'notes/HEARTBEAT-@@BUS@@.md'`)
    .replaceAll(`'farm: ${busName} heartbeat'`, `'farm: @@BUS@@ heartbeat'`)
    .replaceAll('notes/HEARTBEAT-' + busName + '.md`', 'notes/HEARTBEAT-@@BUS@@.md`')
    .replaceAll(`${npmRoot}\\opencode.cmd`, `@@NPMROOT@@\\opencode.cmd`)
    .replaceAll(`${npmRoot}\\cline.cmd`, `@@NPMROOT@@\\cline.cmd`)
    .replaceAll(`${npmRoot}\\kilo.cmd`, `@@NPMROOT@@\\kilo.cmd`);
}
for (const bus of BUSES) {
  const back = unSubstitute(bus, generateWorker(bus));
  assert(back === template, `round-trip ${bus}: generated bytes un-substitute to the template`);
}

// 3. hp's explicit pins carried into the lane table (row build item 1)
const hp = generateWorker('hp');
assert(hp.includes(`DefaultModel = 'meituan/longcat-2.5-preview:free'`) && /ArgFormat\s+= '-z "\{0\}" --provider nous -m \{4\}'/.test(hp),
  'step lane keeps --provider nous beside the rotated model slot (longcat-2.5-preview default)');
assert(hp.includes(`DefaultModel = 'opencode/muse-spark-1.3-contributor-free'`) && hp.includes(`ArgFormat    = 'run -m {4} "{0}"'`),
  'opencode lane keeps opencode/muse-spark-1.3-contributor-free as its default and takes the rotated model as {4}');
assert(/RotateModels = @\('\^opencode\/muse-spark-1\\.3\.\*free\$', '\^opencode\/fledge-alpha\.\*free\$'.*\)/.test(hp)
  && !hp.includes('ling-3\\.0-flash-fin'),
  'opencode lane rotates the 2026-10-06 post-rotation pool: muse-spark-1.3 -> fledge-alpha -> space-bunny -> ling-3.1 -> longcat-2.5-preview (mimo-v2.6 dropped 2026-10-06: probed DEAD UnknownError x3 on ps; ling-3.0-flash-fin still out)');
assert(hp.includes('CloseStdin   = $true') && hp.includes('$proc.StandardInput.Close()'), 'opencode lane closes stdin (the Task Scheduler hang)');
assert(hp.includes('taskkill /PID {0} /T /F'), 'timeout kills the process TREE, not the shim');
assert(hp.includes('$MaxDeferrals = 3'), 'a tasking is failed after 3 deferrals so it cannot hold a lane shut');
assert(hp.includes("Write-Heartbeat -Status 'sync-failed'"), 'a failed git pull still writes a heartbeat');
// FARM-WORKER-DIRTY-TREE-1's five dirty-tree assertions ride with the parked copy under
// research/FARM-WORKER-DIRTY-TREE-1/gen-farm-worker.test.mjs; they turn red against today's
// template and are re-applied with it when that row's rollout leg runs.
// Re-pinned 2026-09-20: the cline lane now rotates (RotateModelsLiteral, model in the {4} slot)
// instead of pinning muse-spark-1.3-contributor inline — the old argv pin would have been wrong.
assert(hp.includes(`RotateModelsLiteral = @('cline-free/muse-spark-1.3-contributor', 'cline-free/deepseek-v4.1-flash', 'cline-free/mimo-v2.6-flash')`),
  'cline lane rotates muse-spark-1.3 -> deepseek-v4.1-flash -> mimo-v2.6-flash, literal ids');
assert(hp.includes(`DefaultModel = 'cline-free/muse-spark-1.3-contributor'`) && /ArgFormat\s+= '--data-dir "\{1\}" -c "\{2\}" -m \{4\} --json -t \{3\} --retries 4 "\{0\}"'/.test(hp),
  'cline lane keeps muse-spark-1.3 as its default and takes the rotated model as {4}');
assert(hp.includes('if (-not $Lane.RotateModels -and -not $Lane.RotateModelsLiteral)'), 'the rotation resolver opts in literal-list lanes');
// Lane-maximization pass (2026-09-20): every lane rotates — no single pinned model anywhere.
// 2026-10-02 hermes/step restore: the 2026-09-20 pair died with the Nous free period; the six
// replacements are the portal's freeRecommendedModels, each probed READY on the Omen that day;
// 2026-10-06 auto-rotate (Part 5) dropped the fleet-wide-404 space-bunny-alpha and trails
// upstage/solar-mini4:free (PS-HERMES-ROTATE-2's Solar add, re-probed READY on ps/nitro/aspire/msi).
assert(hp.includes(`RotateModelsLiteral = @('meituan/longcat-2.5-preview:free', 'inclusionai/ling-3.0-flash-sante:free', 'poolside/laguna-s-2.1:free', 'stepfun/step-3.7-flash:free', 'poolside/laguna-xs-2.1:free', 'upstage/solar-mini4:free')`) && /ArgFormat\s+= '-z "\{0\}" --provider nous -m \{4\}'/.test(hp),
  'hermes lane rotates longcat-2.5-preview -> ling -> laguna-s -> step-3.7 -> laguna-xs -> solar-mini4 (literal, {4} slot)');
assert(!!/^[ ]*RotateModelsLiteral = @\('deepseek-v4\.1-flash'\)$/m.test(hp) && hp.includes('--model {4} --settings'),
  'workbuddy runs DeepSeek v4.1 Flash only (single-id rotation line, {4} slot kept; hy4/hy3/tier aliases dropped — WORKBUDDY-DEEPSEEK-ONLY-1)');
assert((hp.match(/'\^opencode\//g) || []).length === 5, 'opencode lane rotates a 5-pattern catalog pool (2026-10-06 auto-rotate #2: mimo-v2.6 dropped probed-DEAD on ps; pool muse-spark/fledge/space-bunny/ling-3.1/longcat-2.5)');
assert(hp.includes("if ($harness -eq 'step') { $harness = 'hermes' }"), 'legacy step/muse harness names alias to hermes/opencode at claim time');
assert(hp.includes('RequireFile = "$env:LOCALAPPDATA\\Programs\\WorkBuddyAI'), 'workbuddy RequireFile kept (family property)');
assert(hp.includes('FallbackExe'), 'FallbackExe kept (family property hp lacked)');
// KILO-FALLBACK-LANE-1 (2026-10-07): the kilo fallback lane — gateway Auto Free router,
// credential-gated, single-entry literal rotation, auth-fault tails route to DEFERRED.
assert(hp.includes(`RotateModelsLiteral = @('kilo/kilo-auto/free')`) && /ArgFormat\s+= 'run --auto -m \{4\} "\{0\}"'/.test(hp),
  'kilo lane runs the gateway Auto Free router through `kilo run --auto` as a single-entry literal rotation ({4} slot)');
assert(hp.includes('RequireFile = "$env:USERPROFILE\\.local\\share\\kilo\\auth.json"'),
  'kilo RequireFile gates on the gateway credential file: inert (defer, never fail) until the per-machine login');
assert(template.includes('@@NPMROOT@@\\kilo.cmd'), 'kilo FallbackExe uses the per-bus npmRoot token (opencode/cline family property)');
assert(/you need to sign in/.test(hp), 'an auth-fault tail is a transient (DEFERRED), never a permanent .FAILED (pre-login kilo reroutes stay harmless)');

// 4. per-bus identity: distinct bytes, own machine/bus/npmRoot, nothing left unsubstituted
const gen = Object.fromEntries(BUSES.map((b) => [b, generateWorker(b)]));
for (const bus of BUSES) {
  const g = gen[bus];
  assert(!g.includes('@@'), `${bus}: no unsubstituted @@ token`);
  assert(g.includes(`$Machine = '${TOKEN_VALUES[bus]['@@MACHINE@@']}'`), `${bus}: $Machine = ${TOKEN_VALUES[bus]['@@MACHINE@@']}`);
  assert(g.includes(`HEARTBEAT-${bus}.md`) && g.includes(`'farm: ${bus} heartbeat'`), `${bus}: heartbeat filename + commit message carry the bus`);
  assert(g.includes(`${TOKEN_VALUES[bus]['@@NPMROOT@@']}\\opencode.cmd`), `${bus}: npmRoot exe root applied`);
}
const shas = new Set(BUSES.map((b) => createHash('sha256').update(gen[b]).digest('hex')));
assert(shas.size === BUSES.length, `the ${BUSES.length} buses generate ${BUSES.length} distinct byte strings`);

// 5. FARM-HARNESS-ENV-SCRUB-1: the child environment is an allowlist. The env-scrub block is cut
// out of the generated worker and run under real powershell.exe (5.1): a planted secret-named
// parent variable must be ABSENT from a spawned child (which prints its variable NAMES only),
// the passed names are logged, and the launch is refused when a secret name is allowlisted.
const blk = /# ---- env-scrub begin[\s\S]*?# ---- env-scrub end/.exec(hp);
assert(!!blk, 'generated worker carries the env-scrub block');
assert(hp.includes('-EnvAllow @($lane.EnvAllow) -TmpDir (Join-Path $scratchDir \'tmp\')'), 'Invoke-Harness is called with the lane EnvAllow and a per-run TEMP');
assert(hp.includes('Set-ScrubbedEnv -Psi $psi -Extra $Lane.EnvAllow'), 'the model-catalog child is scrubbed too');
if (blk) {
  const dir = mkdtempSync(join(tmpdir(), 'envscrub-'));
  const script = join(dir, 'probe.ps1');
  const ps1 = [
    'param([string]$Mode)',
    'function Write-Log { param([string]$Message) Write-Output ("LOG " + $Message) }',
    blk[0],
    '$env:PLANTED_FAKE_SECRET_TOKEN = "planted-value-not-real"',
    '$env:PLANTED_HARMLESS_NAME = "planted-value-not-real"',
    'if ($Mode -eq "refuse") { $script:EnvAllowBase += "PLANTED_FAKE_SECRET_TOKEN" }',
    '$psi = [System.Diagnostics.ProcessStartInfo]::new()',
    '$psi.FileName = $env:ComSpec',
    '$psi.Arguments = "/c set"',
    '$psi.UseShellExecute = $false; $psi.RedirectStandardOutput = $true',
    'try { Set-ScrubbedEnv -Psi $psi -Extra @() -TmpDir (Join-Path $env:TEMP "envscrub-tmp") } catch { Write-Output ("REFUSED " + $_.Exception.Message); exit 7 }',
    '$p = [System.Diagnostics.Process]::Start($psi); $o = $p.StandardOutput.ReadToEnd(); $p.WaitForExit()',
    'Write-Output $o',
  ].join('\r\n');
  writeFileSync(script, ps1);
  const run = (mode) => spawnSync('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', script, mode], { encoding: 'utf8' });
  const ok = run('ok');
  const childNames = (ok.stdout.match(/^[A-Za-z_][A-Za-z0-9_()]*(?==)/gm) || []);
  assert(ok.status === 0 && childNames.length > 0, `env probe ran under powershell.exe (exit ${ok.status}, ${childNames.length} child variable names)`);
  assert(!childNames.includes('PLANTED_FAKE_SECRET_TOKEN'), 'planted secret-named parent variable is ABSENT from the child');
  assert(!childNames.includes('PLANTED_HARMLESS_NAME'), 'a planted non-allowlisted name is ABSENT from the child too (allowlist, not denylist)');
  assert(childNames.length > 0 && childNames.every((n) => /^(SystemRoot|windir|ComSpec|PATH|PATHEXT|TEMP|TMP|USERPROFILE|HOMEDRIVE|HOMEPATH|APPDATA|LOCALAPPDATA|ProgramFiles|ProgramData|NUMBER_OF_PROCESSORS|PROCESSOR_ARCHITECTURE|OS)$/i.test(n) || /^PROMPT$/i.test(n)),   // PROMPT: cmd.exe synthesizes its own default
    `child carries only allowlisted names (${childNames.join(',')})`);
  assert(/LOG child env names \(\d+\): /.test(ok.stdout) && !ok.stdout.includes('planted-value-not-real'), 'the passed NAMES are logged and no value is');
  assert(!/KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL/i.test((ok.stdout.match(/LOG child env names[^\r\n]*/) || [''])[0]), 'no secret-shaped name in the logged list');
  const refused = run('refuse');
  assert(refused.status === 7 && /REFUSED env scrub self-check: secret-named variable in allowlist: PLANTED_FAKE_SECRET_TOKEN/.test(refused.stdout), `launch refused when a secret name is allowlisted (exit ${refused.status})`);
  rmSync(dir, { recursive: true, force: true });
}
// PowerShell 5.1 parse check on all five generated workers
for (const bus of BUSES) {
  const dir = mkdtempSync(join(tmpdir(), 'parse-'));
  const f = join(dir, 'w.ps1');
  writeFileSync(f, gen[bus]);
  const r = spawnSync('powershell.exe', ['-NoProfile', '-Command', `$e=$null;$t=$null;[void][System.Management.Automation.Language.Parser]::ParseFile('${f}',[ref]$t,[ref]$e);if($e.Count){$e|%{$_.ToString()};exit 1}`], { encoding: 'utf8' });
  assert(r.status === 0, `${bus}: PowerShell 5.1 parse clean${r.status === 0 ? '' : ' ' + r.stdout}`);
  rmSync(dir, { recursive: true, force: true });
}

if (failures.length) {
  console.log(`FAIL — ${failures.length} failing check(s)`);
  process.exit(1);
}
console.log('PASS — gen-farm-worker: golden bytes, token round-trip, hp pins, per-bus identity all hold');
